language: python
env:
  global:
    - CI=true
    
matrix:
  include:
    - os: linux
      python: 3.6
      env: GOLIXINSTALL=full
      
    - os: linux
      python: 3.6
      env: GOLIXINSTALL=partial
      
    - os: linux
      python: 3.5
      env: GOLIXINSTALL=full
      
    - os: linux
      python: 3.5
      env: GOLIXINSTALL=partial
      
    - os: linux
      python: 3.4
      env: GOLIXINSTALL=full
      
    - os: linux
      python: 3.4
      env: GOLIXINSTALL=partial
    
# command to install dependencies
install: |
  if [[ $GOLIXINSTALL == 'full' ]]; then
      pip install .[full]
  else
      pip install .
  fi
  
script: |
  if [[ $GOLIXINSTALL == 'full' ]]; then
      python tests/trashtest.py
  else
      python tests/trashtest_partial.py
  fi

branches:
  only:
    - master